### PR TITLE
Task 3 Web scraping fixes #6

### LINKED ISSUE #6: Task 3 - Web Scraping
Scrape the website https://inshorts.com/en/read/ to create a JSON of all the news on that page. The JSON must have fields title, content & image url

### PR DESCRIPTION
**Pull request by anupm12**

### CODE REVIEW

**Comment by aswinzz** [comment]
@anupm12 Try to remove the \n from the scraped content so that you will have proper content,

**Comment by anupm12** [comment]
@aswinzz I removed \n from the content section.

**Review by Anupam-dagar — CHANGES_REQUESTED** [review]
remove node_modules from your changes. They should be in gitignore

**Comment by anupm12** [comment]
I have reset my machine and so have made a new pr.

**Pull request closed without merging**
