### PR TITLE
Shell Script to change proxy #7

### PR DESCRIPTION
**Pull request by vishnuk7**
Task 4 Solved
issue #7  
image

### CODE REVIEW

**Comment by aswinzz** [comment]
@vishnuk7 This will set proxy only for your current instance of the shell. Try to make it in such a way it is permanent (see .bashrc file for that) and also try to take in input from the user instead of hardcoding values.

**Comment by aswinzz** [comment]
@vishnuk7 This will set proxy only for your current instance of the shell. Try to make it in such a way it is permanent (see .bashrc file for that) and also try to take in input from the user instead of hardcoding values.

**Comment by vishnuk7** [comment]
ok @aswinzz  I will try

**Comment by vishnuk7** [comment]
@aswinzz this issue and issue #29 are the same?

**Comment by aswinzz** [comment]
@vishnuk7 this was for Task 4 right.. I thought of Task 7, in task 7 you have to set system wide proxy. While task 4 sets the proxy for current shell instance.
So i will merge this.

**Pull request merged**
