### PR TITLE
Completed task 8 and task 5

### PR DESCRIPTION
**Pull request by criticic**
completed task 8( #30 ) and task 5 ( #8 )

output for task 8 :
output

output for task 5:
sinewave

### CODE REVIEW

**Comment by criticic** [comment]
I am sorry for multiple commits in one pull request..

**Comment by aswinzz** [comment]
@SagnikMandal You have added task 6 file too, please make different PR for each task.

**Comment by criticic** [comment]
@aswinzz Sorry I am unable to do so...
Please tell me how may I do so?
All these are already in master branch of my fork

**Comment by criticic** [comment]
@aswinzz the PR for those tasks(6 and 10) is already merged by @Jigar3 ( #70 ) ..But still this PR shows those files ...

**Pull request closed without merging**
