### PR TITLE
Completed Task 6 and 10

### PR DESCRIPTION
**Pull request by criticic**
Both Task 6 and 10 are completed
For Task 10 , final output:
spiral

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
Approved task 10.
@Jigar3 review task 6

**Comment by criticic** [comment]
Please review task 6...

**Comment by criticic** [comment]
@Anupam-dagar how do I update points on leaderboard?

**Comment by criticic** [comment]
@Jigar3 Please review Task 6

**Comment by Jigar3** [comment]
@SagnikMandal task 6 looks good. Regarding updating points on leaderboard you need to go to https://opencode19.netlify.com and go to the submit section.

**Pull request merged**
